[package]
name = "snake"
version = "0.1.0"
authors = ["Dmitry Kandalov <dmitry.kandalov@gmail.com>"]

[dependencies]
libc = "0.2.0"
rand = "0.5.5"
maplit = "1.0.1"

[profile.release]
lto = true
panic = 'abort'